# Feature Transformation
<pre>
    2. Handling Categorical Features (Encoding Categorical Data)<br><br>
        1. Oridnal Encoding <br>
        1. One Hot Encoding<br>
            - sklearn ColumnTransformer<br> 
        1. Label Encoding<br><br>
</pre>

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder

In [4]:
df = pd.read_csv("customer.csv")
# Age: Numerical (Discrete); gender, purchased: Categorical (Nominal); review, education: Categorcal (Oridnal)
# Note: The purchased is a output column (i.e., Label). Label encoding is only used for output columns.
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

# Ordinal Encoding

In [7]:
ordinal_data = df[['review','education']]
# Note: The sequence in categories must be organized as per requirement. In this case review: (Poor, Average, Good) = (0,1,2) and 
# (School,UG: Undergraduate, PG: PostGraduate) = (0,1,2)
ordinal = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

ordinal_encoded_data = ordinal.fit_transform(ordinal_data)
ordinal_encoded_data


array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [12]:
ordinal.categories_
# 0: Poor, 1: Average, 2: Good;  0: School, UG: 1, PG: 2;

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# One Hot Encoding

In [15]:
data = pd.read_csv("cars.csv")
data

brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [20]:
data['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [21]:
data['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [24]:
ohe_data = pd.DataFrame(data[['fuel','owner']])
ohe_data

fuel                 owner
0     Diesel           First Owner
1     Diesel          Second Owner
2     Petrol           Third Owner
3     Diesel           First Owner
4     Petrol           First Owner
...      ...                   ...
8123  Petrol           First Owner
8124  Diesel  Fourth & Above Owner
8125  Diesel           First Owner
8126  Diesel           First Owner
8127  Diesel           First Owner

[8128 rows x 2 columns]

In [33]:
# Note one hot encoding is used for Categorical Nominal Data. You can customize as per your need.
# drop = 'First' column technique. 100, 010, 001 = 00, 10, 01
ohe = OneHotEncoder()
ohe_encoded_data = ohe.fit_transform(ohe_data)
ohe_encoded_data

<8128x9 sparse matrix of type '<class 'numpy.float64'>'
	with 16256 stored elements in Compressed Sparse Row format>

In [34]:
ohe_encoded_data.toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [37]:

# fuel
# 0. Diesel    4402
# 1. Petrol    3631
# 2. CNG         57
# 3. LPG         38

# owner
# 4 First Owner             5289
# 5. Second Owner            2105
# 6. Third Owner              555
# 7. Fourth & Above Owner     174
# 8. Test Drive Car             5


ohe_df = pd.DataFrame(ohe_encoded_data.toarray())
ohe_df

0    1    2    3    4    5    6    7    8
0     0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1     0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
3     0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
8123  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
8124  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8125  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8126  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8127  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[8128 rows x 9 columns]

## One Hot Encoding Using Pandas

In [40]:
dummies = pd.get_dummies(data[['fuel','owner']])
dummies

fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  owner_First Owner  \
0        False         True     False        False               True   
1        False         True     False        False              False   
2        False        False     False         True              False   
3        False         True     False        False               True   
4        False        False     False         True               True   
...        ...          ...       ...          ...                ...   
8123     False        False     False         True               True   
8124     False         True     False        False              False   
8125     False         True     False        False               True   
8126     False         True     False        False               True   
8127     False         True     False        False               True   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  
0                 False  
1                 False  
2                  True  
3                 False  
4                 False  
...                 ...  
8123              False  
8124              False  
8125              False  
8126              False  
8127              False  

[8128 rows x 9 columns]

In [41]:
data = data + dummies
data

brand fuel  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  km_driven  \
0      NaN  NaN       NaN          NaN       NaN          NaN        NaN   
1      NaN  NaN       NaN          NaN       NaN          NaN        NaN   
2      NaN  NaN       NaN          NaN       NaN          NaN        NaN   
3      NaN  NaN       NaN          NaN       NaN          NaN        NaN   
4      NaN  NaN       NaN          NaN       NaN          NaN        NaN   
...    ...  ...       ...          ...       ...          ...        ...   
8123   NaN  NaN       NaN          NaN       NaN          NaN        NaN   
8124   NaN  NaN       NaN          NaN       NaN          NaN        NaN   
8125   NaN  NaN       NaN          NaN       NaN          NaN        NaN   
8126   NaN  NaN       NaN          NaN       NaN          NaN        NaN   
8127   NaN  NaN       NaN          NaN       NaN          NaN        NaN   

     owner  owner_First Owner  owner_Fourth & Above Owner  owner_Second Owner  \
0      NaN                NaN                         NaN                 NaN   
1      NaN                NaN                         NaN                 NaN   
2      NaN                NaN                         NaN                 NaN   
3      NaN                NaN                         NaN                 NaN   
4      NaN                NaN                         NaN                 NaN   
...    ...                ...                         ...                 ...   
8123   NaN                NaN                         NaN                 NaN   
8124   NaN                NaN                         NaN                 NaN   
8125   NaN                NaN                         NaN                 NaN   
8126   NaN                NaN                         NaN                 NaN   
8127   NaN                NaN                         NaN                 NaN   

      owner_Test Drive Car  owner_Third Owner  selling_price  
0                      NaN                NaN            NaN  
1                      NaN                NaN            NaN  
2                      NaN                NaN            NaN  
3                      NaN                NaN            NaN  
4                      NaN                NaN            NaN  
...                    ...                ...            ...  
8123                   NaN                NaN            NaN  
8124                   NaN                NaN            NaN  
8125                   NaN                NaN            NaN  
8126                   NaN                NaN            NaN  
8127                   NaN                NaN            NaN  

[8128 rows x 14 columns]

# Label Encoding

In [10]:
# Label encoding is used for the output categorical column. In this case purchased.
label_column = df['purchased']
le = LabelEncoder()
label_encoded_column= le.fit_transform(label_column)
label_encoded_column

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [14]:
le.classes_
# 0: No, 1: Yes;

array(['No', 'Yes'], dtype=object)